apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jyapi8ijr-java-springboot
  janus-idp.io/tekton: jyapi8ijr-java-springboot
  backstage.io/kubernetes-id: jyapi8ijr-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jyapi8ijr-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
